---
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: initialize the cluster
  shell: kubeadm init --kubernetes-version 1.26.1 \
    --pod-network-cidr=172.16.20.0/24 \
    -v=5 >> cluster_initialized.txt
  become: yes
  become_user: root
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: samcaldwell
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/samcaldwell/.kube/config
    remote_src: yes
    owner: samcaldwell

- name: check for pod_network_setup.txt
  stat:
    path: pod_network_setup.txt
  register: pod_network_setup

- name: copy kube-flannel.yml to control node
  copy:
    src: "/Users/samcaldwell/git/datacollectors/ansible/kube-cluster/kube-flannel.yml"
    dest: "kube-flannel.yml"
    validate: /usr/sbin/visudo -csf %s

- name: check for kube_flannel.yml
  stat:
    path: kube_flannel.yml

- name: install Pod network
  become: yes
  become_user: samcaldwell
  shell: kubectl apply -f kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt
