---
- name: check for node_joined.txt
  stat:
    path: node_joined.txt
  register: node_joined_exists

- name: join cluster
  shell: "{{ hostvars['control00'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: node_joined_exists.stat.exists == false
