version: "2"
#
#
#
services:

  kafka-0:
    image: datacollectors_kafka:local
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_0_data:/bitnami/kafka
    depends_on:
      - zookeeper

  kafka-1:
    image: datacollectors_kafka:local
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_1_data:/bitnami/kafka
    depends_on:
      - zookeeper

  kafka-2:
    image: datacollectors_kafka:local
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=2
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_2_data:/bitnami/kafka
    depends_on:
      - zookeeper

  postgresql:
    image: postgresql:local
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=vitapro
      - POSTGRESQL_DATABASE=my_database

  redis:
    image: redis:local
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      - REDIS_PASSWORD=vitapro
      - REDIS_MASTER_PASSWORD=vitapro

  zookeeper:
    image: zookeeper:local
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
#
#
#
volumes:
  kafka_0_data:
    driver: local

  kafka_1_data:
    driver: local

  kafka_2_data:
    driver: local

  postgresql_master_data:
    driver: local

  zookeeper_data:
    driver: local
