#
#
#

#POSTGRES_DOCKER_SERVER_START_FLAGS:=-it
#POSTGRES_DOCKER_SERVER_ENTRYPOINT:= --entrypoint ''
#POSTGRES_DOCKER_SERVER_CMD:=/bin/bash

POSTGRES_DOCKER_SERVER_START_FLAGS:=-d --rm
POSTGRES_DOCKER_SERVER_ENTRYPOINT:= --entrypoint '/opt/server_entrypoint.sh'
POSTGRES_DOCKER_SERVER_CMD:=''

db/start/server: db/stop/server db/build/server
	docker run $(POSTGRES_DOCKER_SERVER_START_FLAGS) \
	   --publish $(POSTGRESQL_DB_HOST):$(POSTGRESQL_DB_PORT):$(POSTGRESQL_DB_PORT) \
	   --name $(POSTGRES_SERVER_CONTAINER) \
	   -e POSTGRESQL_VERSION=$(POSTGRESQL_VERSION) \
	   -e POSTGRESQL_DB_PORT=$(POSTGRESQL_DB_PORT) \
	   -e POSTGRESQL_DB_NAME=$(POSTGRESQL_DB_NAME) \
	   -e POSTGRESQL_DB_USER=$(POSTGRESQL_DB_USER) \
	   -e POSTGRESQL_DB_PASS=$(POSTGRESQL_DB_PASS) \
	   $(POSTGRES_DOCKER_SERVER_ENTRYPOINT) \
	   --volume $(CUR_DIR)/storage/db:/var/lib/postgresql \
       $(POSTGRES_SERVER_IMAGE) $(POSTGRES_DOCKER_SERVER_CMD); \
    sleep 2; \
    docker ps

