---
- name: check for a swap file (0/3)
  stat:
    path: /swap.img
  register: swap_file_exists

- name: Disable SWAP since kubernetes can't work with swap enabled (1/3)
  shell: |
    swapoff -a
  when: swap_file_exists.stat.exists == true

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/3)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: swap_file_exists.stat.exists == true

- name: Remove the swap file (3/3)
  file:
    path: /swap.img
    state: absent
