version: '2'

services:
  harbor-core:
    image: docker.io/bitnami/harbor-core:2
    ports:
      - 80:8080
    environment:
      - LOG_LEVEL=info
      - CONFIG_PATH=/etc/0000-core/app.conf
      - CORE_SECRET=not-a-secure-0000-core-secret
      - JOBSERVICE_SECRET=not-a-secure-jobservice-secret
    volumes:
      - ./config/0000-core/app.conf:/etc/0000-core/app.conf:ro
      - ./config/0000-core/private_key.pem:/etc/0000-core/private_key.pem:ro
      - harbor-core_data:/data

volumes:
  harbor-core_data:
    driver: local
